<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <ApplicationVersion>1.0.3.0</ApplicationVersion>
    <Version>1.0.3</Version>
    <AppLanguage Condition="'$(AppLanguage)' == ''">ko</AppLanguage>
    <Company>eslee</Company>
    <Product>eslee Auto Power</Product>
  </PropertyGroup>
  <PropertyGroup Condition="'$(AppLanguage)' == 'en'">
    <DefineConstants>$(DefineConstants);APP_LANGUAGE_EN</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(AppLanguage)' != 'en'">
    <DefineConstants>$(DefineConstants);APP_LANGUAGE_KO</DefineConstants>
  </PropertyGroup>
</Project>
