<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AutoPower.Core\AutoPower.Core.csproj" />
    <ProjectReference Include="..\AutoPower.Data\AutoPower.Data.csproj" />
    <ProjectReference Include="..\AutoPower.Windows\AutoPower.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\eslee-auto-power.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\eslee-auto-power.ico" />
    <Resource Include="Assets\eslee-auto-power.png" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AutoPower.Tests" />
  </ItemGroup>

</Project>
