<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AutoPower.Core\AutoPower.Core.csproj" />
    <ProjectReference Include="..\AutoPower.Data\AutoPower.Data.csproj" />
    <ProjectReference Include="..\AutoPower.Windows\AutoPower.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
