<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AutoPower.Core\AutoPower.Core.csproj" />
    <ProjectReference Include="..\..\src\AutoPower.Data\AutoPower.Data.csproj" />
    <ProjectReference Include="..\..\src\AutoPower.Windows\AutoPower.Windows.csproj" />
  </ItemGroup>

</Project>
